### ISSUE TITLE
Document collections.posts

### ISSUE THREAD

**Issue by cfjedimaster** [rknightuk/eleventy-plugin-post-graph#2]
In the docs, it shows either using collections.posts to the shorttag, or custom data. But is there anything in particular in regards to collections.posts that folks should know about? I assume it has to have a date value?

**Comment by cjerrington** [comment]
Not all of my posts have a `date: 2023-12-19` in the `post.data.date`. Locally I found the line and updated it to `const postDate = post.data.date || post.date` and it gets the date from the file name as my blog posts are `2023-12-19-blog-post-title.md`. 

@rknightuk Would you like a pull request to check this out? Once I added this I was able to get the full graph of my posts this year without going back and adding a `date` to the data. 

This is with the change to look at `post.data.date` and `post.date`
![Screenshot from 2023-12-19 21-44-22](https://github.com/rknightuk/eleventy-plugin-post-graph/assets/8809376/f46e5f9c-f4f1-4042-9d95-4fbe09101b86)

This is with only `post.data.date`, and my initial attempt to add the `date` to the front matter. 
![Screenshot from 2023-12-19 21-45-37](https://github.com/rknightuk/eleventy-plugin-post-graph/assets/8809376/d09f2fb2-13a6-48d2-ab67-2503f45afeda)

**Comment by rknightuk** [comment]
@cjerrington That would be great, I did try this with a bunch of sites but didn't come across this.

**Comment by rknightuk** [comment]
@cjerrington I've added this while I was fixing something else, v1.0.2 checks for `post.date` if `post.data.date` doesn't exist.

**Comment by cfjedimaster** [comment]
Just to be clear though - my ask here was to _document_ the requirement. I mean, it's mostly obvious, but as it wasn't called out, I wasn't sure. Can we re-open this please?

**Comment by rknightuk** [comment]
Yep absolutely, sorry I jumped to fixing @cjerrington suggestion and forgot about the original issue 😊
