### ISSUE TITLE
Strange "false" line between CSS and HTML

### ISSUE THREAD

**Issue by bobmonsour** [rknightuk/eleventy-plugin-post-graph#6]
While working out some of my own issues to get the plugin working in my context. I noticed what appears to be an errant line with the word "false" on it between the CSS and HTML generated by the plugin. I'm attaching a screen grab of a portion.
![CleanShot 2023-12-21 at 16 37 18@2x](https://github.com/rknightuk/eleventy-plugin-post-graph/assets/133979/fdc253d0-9600-4397-bffb-8d3404608b84)

**Comment by bobmonsour** [comment]
Robb, this is closable...I got the plugin working well and I don't know how that got generated. I failed to take the time to reproduce it or share my setup. Feel free to close and/or delete this as a non-issue. Awesome plugin!

**Comment by rknightuk** [comment]
That is odd, there's nothing in the code that should output anything there 🤔 Glad you got it sorted Bob
