### ISSUE TITLE
noLabels option generates 'false' line in CSS when not set to true

### ISSUE THREAD

**Issue by bobmonsour** [rknightuk/eleventy-plugin-post-graph#8]
When the noLabels option is left to its default setting of false, it generates a line in the CSS of 'false' rather than being silent, resulting in a CSS validation error. When it is set to true, the option setting works correctly. 

I tracked it down to this line in your plugin:

```
${options.noLabels && `
        .${prefix}__year, .${prefix}__months { display: none; }
    `}
```

It should probably be something like this: 

```
${options.noLabels ? `.${prefix}__year, .${prefix}__months { display: none; }` : ''}
```

**Comment by rknightuk** [comment]
1.0.7 fixes this Bob 👍
